---
version: '3.2'
services:
  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: service
      MYSQL_USER: app
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    image: mysql:5.6
    ports:
      - target: 3306
        published: 3306
    restart: always
    volumes:
      - /opt/datastore:/var/lib/mysql
      - ./mysql_conf.d:/etc/mysql/conf.d
      - /etc/pki:/etc/pki

  redis:
    container_name: redis
    image: redis:4
    ports:
      - target: 6379
        published: 6379
    restart: always

  web:
    container_name: web
    entrypoint:
      - sh
      - -cl
      - "cd /root/ansistrano-symfony3 && ansible-playbook deploy_without_ansistrano.yml -i inventories/development -vvv --extra-vars '{\"is_container\": true, \"symfony_env\": \"${SYMFONY_ENV}\"}' && /usr/sbin/httpd -D FOREGROUND"
    environment:
      SYMFONY_DATABASE_HOST: mysql
      SYMFONY_DATABASE_PASSWORD: ${DATABASE_USER_PASSWORD}
      SYMFONY_MYSQL_CA: ${SYMFONY_MYSQL_CA}
      SYMFONY_REDIS_DSN_DEFAULT: redis://redis/0
      SYMFONY_REDIS_DSN_CACHE: redis://redis/1
      SYMFONY_REDIS_DSN_SESSION: redis://redis/2
      SYMFONY_REDIS_DSN_STORAGE: redis://redis/3
      SYMFONY_SECRET: ${SYMFONY_SECRET}
      SYMFONY_ENV: ${SYMFONY_ENV?err}
    image: futureys/symfony3:1.201807.23
    links:
      - mysql
      - redis
    ports:
      - 80:80
    # restart: always
    volumes:
      - /etc/pki:/etc/pki
      - ./ansistrano-symfony3:/root/ansistrano-symfony3
      - ./symfony3-codeanywhere:/root/workspace/repo
      - /tmp/symfony3/var/cache:/root/workspace/repo/var/cache
      - /tmp/symfony3/var/logs:/root/workspace/repo/var/logs
      - /tmp/symfony3/var/sessions:/root/workspace/repo/var/sessions
